### ISSUE TITLE
Cannot read property 'replace' of null - gist.description

### ISSUE THREAD

**Issue by coeus01** [stefanoschrs/gistbot#1]
```
/xxx/gistbot/gistbot.js:76
                    gist.description = gist.description.replace(/\n/g, ' ');
                                                       ^

TypeError: Cannot read property 'replace' of null
    at /xxx/gistbot/gistbot.js:76:41
    at /xxx/gistbot/gistbot.js:37:12
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

```

**Comment by stefanoschrs** [comment]
Thanks for pointing out. This is not a stable version yet so probably there are more like this one. 
Fix in commit https://github.com/stefanoschrs/gistbot/commit/b91ab009f5ebfc7a8a06549213e49d5e523d72b8
